python_test(
    name = "preflight_worker_test",
    srcs = [
        "preflight_worker.py",
        "preflight_worker_test.py",
    ],
    base_module = "",
    deps = ["//tools:_isolation"],
)

python_test(
    name = "reapi_readiness_test",
    srcs = [
        "reapi_readiness.py",
        "reapi_readiness_test.py",
    ],
    base_module = "",
)

python_test(
    name = "prepare_worker_probe_root_test",
    srcs = [
        "prepare_worker_probe_root.py",
        "prepare_worker_probe_root_test.py",
    ],
    base_module = "",
)
