load("//defs:flavor.bzl", "package")
load("//defs:architectures.bzl", "ARCHITECTURES", "DEFAULT_ARCHITECTURE", "execution_compatible_with", "release_arch_suffix", "target_platform")
load("//defs:releases.bzl", "default_release", "flavor_releases")
load(
    "//defs:rpm_family.bzl",
    "rpm_buildroot_target",
    "rpm_buildroots_for",
    "rpm_downloads_for",
    "rpm_packages_for",
    "rpm_rootfs_for",
)
load("//flavors/centos/generated:index.bzl", "DATA_BY_RELEASE_ARCH")

RELEASES = flavor_releases("centos", default = "9,10")
DEFAULT_RELEASE = default_release("centos", RELEASES)

rpm_downloads_for("centos", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE_ARCH)
rpm_buildroots_for("centos", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE_ARCH)
rpm_packages_for("centos", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE_ARCH)
rpm_rootfs_for("centos", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE_ARCH)

[
    package(
        name = "hello-{}-{}".format(_release, _arch),
        flavor = "centos",
        srpm = "//tests:hello-srpm",
        source_name = "hello",
        version = "1.0",
        release = "1",
        subpackages = ["hello"],
        defines = ["debug_package %{nil}"],
        buildroot = rpm_buildroot_target("centos", release_arch_suffix(_release, _arch)),
        supplier = "Organization: CentOS",
        default_target_platform = target_platform("centos", _release, _arch),
        exec_compatible_with = execution_compatible_with(_arch),
        visibility = ["PUBLIC"],
    )
    for _release in RELEASES
    for _arch in ARCHITECTURES
]

package(
    name = "hello-9",
    flavor = "centos",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos", "-9"),
    supplier = "Organization: CentOS",
    default_target_platform = target_platform("centos", "9", DEFAULT_ARCHITECTURE),
    exec_compatible_with = execution_compatible_with(DEFAULT_ARCHITECTURE),
    visibility = ["PUBLIC"],
)

package(
    name = "hello-10",
    flavor = "centos",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos", "-10"),
    supplier = "Organization: CentOS",
    default_target_platform = target_platform("centos", "10", DEFAULT_ARCHITECTURE),
    exec_compatible_with = execution_compatible_with(DEFAULT_ARCHITECTURE),
    visibility = ["PUBLIC"],
)

package(
    name = "hello",
    flavor = "centos",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos", ""),
    supplier = "Organization: CentOS",
    default_target_platform = target_platform("centos", DEFAULT_RELEASE, DEFAULT_ARCHITECTURE),
    exec_compatible_with = execution_compatible_with(DEFAULT_ARCHITECTURE),
    visibility = ["PUBLIC"],
)
