load("//defs:releases.bzl", "default_release", "flavor_releases")
load(
    "//defs:deb_family.bzl",
    "deb_buildroots_for",
    "deb_downloads_for",
    "deb_packages_for",
)
load("//flavors/debian/generated:index.bzl", "DATA_BY_RELEASE")

RELEASES = flavor_releases("debian", default = "13")
DEFAULT_RELEASE = default_release("debian", RELEASES)

deb_downloads_for("debian", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
deb_buildroots_for("debian", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
deb_packages_for("debian", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
