#!/usr/bin/env python3
"""Generate pure Starlark data from a Debian-family lockfile."""

import argparse
import json
import logging
import os


LOG = logging.getLogger("deb-generate")


def bzl_literal(value, indent=0):
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, dict):
        if not value:
            return "{}"
        pad = " " * indent
        child = " " * (indent + 4)
        lines = [
            "{}{}: {},".format(child, bzl_literal(key), bzl_literal(item, indent + 4))
            for key, item in sorted(value.items())
        ]
        return "{\n" + "\n".join(lines) + "\n" + pad + "}"
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        pad = " " * indent
        child = " " * (indent + 4)
        lines = [
            "{}{},".format(child, bzl_literal(item, indent + 4))
            for item in value
        ]
        return "[\n" + "\n".join(lines) + "\n" + pad + "]"
    return json.dumps(value)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("lockfile")
    parser.add_argument("--output", default=None)
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="deb-generate: %(message)s",
    )

    with open(args.lockfile, encoding="utf-8") as stream:
        lock = json.load(stream)
    if lock.get("schema") != 1:
        raise SystemExit("unsupported Debian-family lock schema: {}".format(lock.get("schema")))
    distro = lock.get("distro")
    if distro not in ("debian", "ubuntu"):
        raise SystemExit("unsupported Debian-family distro: {}".format(distro))

    output = args.output
    if output is None:
        repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        output = os.path.join(
            repo,
            "flavors",
            distro,
            "generated",
            "{}-{}.bzl".format(distro, lock["release"]),
        )

    content = [
        "# @generated by tools/deb_generate.py from {}".format(args.lockfile),
        "# Do not edit by hand.",
        "",
        "DISTRO = {}".format(bzl_literal(distro)),
        "RELEASE = {}".format(bzl_literal(lock["release"])),
        "CODENAME = {}".format(bzl_literal(lock["codename"])),
        "ARCHITECTURE = {}".format(bzl_literal(lock["architecture"])),
        "",
        "SEED_DEBS = {}".format(bzl_literal(lock["seed_debs"])),
        "",
        "SOURCES = {}".format(bzl_literal(lock["sources"])),
        "",
    ]
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8") as stream:
        stream.write("\n".join(content))
    LOG.info("wrote %s", output)


if __name__ == "__main__":
    main()
