#!/usr/bin/env python3
"""Generate pure Starlark data from a Debian-family lockfile."""

import argparse
import json
import logging
import os

from source_policy import validate_source_policy


LOG = logging.getLogger("deb-generate")
ARCHITECTURES = ("x86_64", "aarch64")


def target_cpu(architecture):
    return {"amd64": "x86_64", "arm64": "aarch64"}.get(architecture)


def bzl_literal(value, indent=0):
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, dict):
        if not value:
            return "{}"
        pad = " " * indent
        child = " " * (indent + 4)
        lines = [
            "{}{}: {},".format(child, bzl_literal(key), bzl_literal(item, indent + 4))
            for key, item in sorted(value.items())
        ]
        return "{\n" + "\n".join(lines) + "\n" + pad + "}"
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        pad = " " * indent
        child = " " * (indent + 4)
        lines = [
            "{}{},".format(child, bzl_literal(item, indent + 4))
            for item in value
        ]
        return "[\n" + "\n".join(lines) + "\n" + pad + "]"
    return json.dumps(value)


def validate_lock(lock):
    schema = lock.get("schema")
    if schema not in (2, 3):
        raise ValueError("unsupported Debian-family lock schema: {}".format(schema))
    distro = lock.get("distro")
    if distro not in ("debian", "ubuntu"):
        raise ValueError("unsupported Debian-family distro: {}".format(distro))
    cpu = lock.get("target_cpu") or target_cpu(lock.get("architecture"))
    if cpu not in ARCHITECTURES:
        raise ValueError("unsupported Debian-family target CPU: {}".format(cpu))
    if schema == 3:
        producers = {
            "{}@{}".format(source["name"], source["version_full"])
            for source in lock["sources"]
        }
        validate_source_policy(
            lock.get("source_policy", {}),
            lock.get("image_sets", {}),
            producers,
        )
    return distro, cpu


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("lockfile")
    parser.add_argument("--output", default=None)
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="deb-generate: %(message)s",
    )

    with open(args.lockfile, encoding="utf-8") as stream:
        lock = json.load(stream)
    try:
        distro, cpu = validate_lock(lock)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    output = args.output
    if output is None:
        repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        output = os.path.join(
            repo,
            "flavors",
            distro,
            "generated",
            "{}-{}-{}.bzl".format(distro, lock["release"], cpu),
        )

    content = [
        "# @generated by tools/deb_generate.py from {}".format(args.lockfile),
        "# Do not edit by hand.",
        "",
        "DISTRO = {}".format(bzl_literal(distro)),
        "RELEASE = {}".format(bzl_literal(lock["release"])),
        "CODENAME = {}".format(bzl_literal(lock["codename"])),
        "ARCHITECTURE = {}".format(bzl_literal(lock["architecture"])),
        "TARGET_CPU = {}".format(bzl_literal(cpu)),
        "",
        "BASE_DEBS = {}".format(bzl_literal(lock.get("base_debs", lock.get("seed_debs", [])))),
        "SEED_DEBS = BASE_DEBS",
        "",
        "IMAGE_SETS = {}".format(bzl_literal(lock.get("image_sets", {}))),
        "",
        "SOURCE_POLICY = {}".format(bzl_literal(lock.get("source_policy", {}))),
        "",
        "SOURCES = {}".format(bzl_literal(lock["sources"])),
        "",
    ]
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8") as stream:
        stream.write("\n".join(content))
    LOG.info("wrote %s", output)
    write_index(os.path.dirname(output), distro)


def _identifier(text):
    return "".join(char if char.isalnum() else "_" for char in text)


def write_index(out_dir, distro):
    entries = []
    prefix = distro + "-"
    for name in os.listdir(out_dir):
        if not name.startswith(prefix) or not name.endswith(".bzl"):
            continue
        stem = name[len(prefix):-len(".bzl")]
        release, separator, cpu = stem.rpartition("-")
        if not separator or cpu not in ARCHITECTURES:
            continue
        entries.append((release, cpu, name))
    entries.sort()

    lines = ["# @generated by tools/deb_generate.py. Do not edit.\n\n"]
    for release, cpu, filename in entries:
        alias = "_r{}_{}".format(_identifier(release), cpu)
        lines.append(
            'load(\n'
            '    ":{filename}",\n'
            '    {a}_architecture = "ARCHITECTURE",\n'
            '    {a}_base = "BASE_DEBS",\n'
            '    {a}_codename = "CODENAME",\n'
            '    {a}_distro = "DISTRO",\n'
            '    {a}_image_sets = "IMAGE_SETS",\n'
            '    {a}_release = "RELEASE",\n'
            '    {a}_seed = "SEED_DEBS",\n'
            '    {a}_source_policy = "SOURCE_POLICY",\n'
            '    {a}_sources = "SOURCES",\n'
            '    {a}_target_cpu = "TARGET_CPU",\n'
            ')\n'.format(filename=filename, a=alias)
        )

    by_release = {}
    for release, cpu, _filename in entries:
        by_release.setdefault(release, []).append(cpu)
    lines.append("\nDATA_BY_RELEASE_ARCH = {\n")
    for release in sorted(by_release):
        lines.append('    "{}": {{\n'.format(release))
        for cpu in sorted(by_release[release]):
            alias = "_r{}_{}".format(_identifier(release), cpu)
            lines.append(
                '        "{cpu}": struct(\n'
                '            ARCHITECTURE = {a}_architecture,\n'
                '            BASE_DEBS = {a}_base,\n'
                '            CODENAME = {a}_codename,\n'
                '            DISTRO = {a}_distro,\n'
                '            IMAGE_SETS = {a}_image_sets,\n'
                '            RELEASE = {a}_release,\n'
                '            SEED_DEBS = {a}_seed,\n'
                '            SOURCE_POLICY = {a}_source_policy,\n'
                '            SOURCES = {a}_sources,\n'
                '            TARGET_CPU = {a}_target_cpu,\n'
                '        ),\n'.format(cpu=cpu, a=alias)
            )
        lines.append("    },\n")
    lines.append("}\n\n")
    lines.append("DATA_BY_RELEASE = {\n")
    for release in sorted(by_release):
        if "x86_64" in by_release[release]:
            lines.append(
                '    "{0}": DATA_BY_RELEASE_ARCH["{0}"]["x86_64"],\n'.format(release)
            )
    lines.append("}\n")
    with open(os.path.join(out_dir, "index.bzl"), "w", encoding="utf-8") as stream:
        stream.write("".join(lines))


if __name__ == "__main__":
    main()
