#!/usr/bin/env python3
"""The generate step: lockfile -> checked-in Buck data.

Middle stage of the solve / generate / build split (SPEC.md section 3a).
`solve.py` reads pinned repodata and writes a lockfile; this reads that
lockfile and writes a `.bzl` that the build graph loads.

Two properties matter more than convenience here:

  * The output is *pure data* -- lists of dicts, no rule calls, no logic.
    Everything that turns data into targets stays in handwritten macros in
    flavors/fedora/defs.bzl, where it can be read and tested.  A generator
    that emits logic produces diffs nobody reviews.

  * The output is checked in.  That is the point of the split: the network
    is touched by a human running this, never by a build action, so a
    clean checkout builds offline and any change to what gets built shows
    up as a reviewable diff -- the cargo-vendor / reindeer pattern.

Usage:
    tools/generate.py flavors/fedora/lock/fedora-43.lock.json
    tools/generate.py flavors/fedora/lock/*.lock.json
"""

import argparse
import json
import os
import sys

# The one definition, imported rather than repeated: solve.py writes the
# schema this reads, and a version that lives in two files is a version
# that gets bumped in one.
from solve import LOCK_SCHEMA

HEADER = '''\
# @generated by tools/generate.py from {lockfile}
# Do not edit.  Re-run:
#     tools/generate.py {lockfile}
#
# Pure data, deliberately: flavors/fedora/defs.bzl turns it into targets.
# Every sha256 here is a pin carried through from the lockfile, and it is
# what the http_file targets verify against, so a mirror that serves the
# wrong bytes fails the build rather than poisoning it.

'''


# What buck2 accepts in a target name.  rpm's version grammar produces two
# characters that are not on this list, and both are ordinary rather than
# exotic:
#
#   `:`  an epoch, as in 1:2.12-43.
#   `^`  a post-release marker.  Fedora writes downgrades as
#        2.44.6^really2.44.4, meaning "sorts below what it looks like",
#        and gdk-pixbuf2 carries exactly that today.
#
# The `^` case is the one that bit.  URL escaping for it was already in
# place -- flavors/fedora/defs.bzl percent-encodes it -- with a comment
# saying no pin carried one yet and it was handled rather than waited for.
# The target name was not, so widening the build set turned "handled" into
# a parse error naming a character nobody had connected to rpm.
_TARGET_SAFE = frozenset(
    "abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "0123456789"
    ",.=-/~@!+$_"
)


def target_safe(text):
    """Map anything buck2 will not take in a target name to an underscore.

    Lossy on purpose, and safe to be: the sha256 is what identifies an rpm,
    and flavors/fedora/defs.bzl refuses two pins that collapse to one
    target name with different digests.  So a collision is a loud failure
    rather than a silently shared download.
    """
    return "".join(char if char in _TARGET_SAFE else "_" for char in text)


def _target_name(entry):
    """Buck target name for one binary rpm.

    Includes the arch because noarch and x86_64 builds of the same package
    name coexist in a repo, and version-release because two releases of
    the same distro can be in one graph at once.
    """
    return target_safe("rpm-{}-{}-{}".format(
        entry["name"], entry["evr"], entry["arch"]
    ))


def _dedupe(entries):
    """Collapse entries that name the same blob.

    A seed closure is per-package, and neighbouring packages share nearly
    all of theirs, so the union across a release is far smaller than the
    sum.  Keyed on sha256 so identical content is fetched once.
    """
    by_sha = {}
    for entry in entries:
        by_sha.setdefault(entry["sha256"], entry)
    return [by_sha[k] for k in sorted(by_sha)]


def collect(lock):
    """Split a lockfile into the lists the macros consume."""
    packages = lock["packages"]

    # `buildroot_seed`, not the union of per-package `deps_seed`: the
    # buildroot has to be a complete, self-consistent tree, so it includes
    # prebuilt copies of the packages this repo also rebuilds.  See the
    # comment on seed_closure in tools/solve.py.
    seed = _dedupe(lock["buildroot_seed"])

    # Runtime closures, one per --image.  Deduped within a set but not
    # across sets or against the seed: each set has to stay a complete
    # install list, and the sharing is recovered at the target level, where
    # _target_name is a function of (name, evr, arch) and so two sets
    # naming the same rpm resolve to the same http_file.
    image_sets = {
        name: _dedupe(members)
        for name, members in sorted(lock.get("image_sets", {}).items())
    }

    sources = []
    recipes = []
    for name in sorted(packages):
        pkg = packages[name]
        source = pkg["source"]
        sources.append({
            "name": source["name"],
            "evr": source["evr"],
            "location": source["location"],
            "sha256": source["sha256"],
            "repo": source.get("repo"),
        })
        recipes.append({
            "name": name,
            "source_name": source["name"],
            "evr": source["evr"],
            "subpackages": pkg.get("subpackages", [name]),
            # Deps that come from other source packages we build.  Kept
            # separate from the seed because these become target refs,
            # not downloads.
            "build_deps": sorted({
                dep["name"] for dep in pkg.get("deps_built", [])
            }),
        })

    # The cycle-breaking plan, carried through verbatim.  Deciding it is
    # the solver's job -- which packages form a cycle, how many stages
    # break it, and what each stage builds against -- and re-deriving any
    # of that here would put a second opinion in the graph.
    staged = [
        {
            "target": entry["target"],
            "source": entry["source"],
            "stage": entry["stage"],
            "ships": entry["ships"],
            "cycle_deps": sorted(entry.get("cycle_deps", [])),
            "cycle_deps_from": entry["cycle_deps_from"],
        }
        for entry in sorted(
            lock.get("staged", []),
            key=lambda e: (e["stage"], e["source"]),
        )
    ]

    return seed, image_sets, sources, recipes, staged


def render(lock, lockfile, seed, image_sets, sources, recipes, staged):
    out = [HEADER.format(lockfile=lockfile)]
    out.append("RELEASE = {}\n".format(json.dumps(lock["release"])))
    out.append("DIST_TAG = {}\n".format(json.dumps(lock["dist_tag"])))
    out.append("TARGET_CPU = {}\n".format(json.dumps(lock["target_cpu"])))
    out.append("\n")

    # The upstream URL each repo's `location` paths are relative to.  Carried
    # from the lockfile rather than reconstructed here, because a repo-relative
    # location does not say which repo it came from and the repodata that
    # would answer that is not checked in.
    #
    # A map rather than one binary and one source base: once updates/ is
    # layered over releases/, a single closure legitimately spans both, so
    # the base has to be looked up per entry.  Every entry below carries the
    # repo name that indexes this.
    #
    # Canonical upstream, not whatever mirror served the solve: a mirror is
    # substitutable at build time precisely because the sha256 is pinned, so
    # baking one in would trade a fact for a local accident.
    out.append("REPO_BASE = {\n")
    for repo in sorted(lock.get("repos", []), key=lambda r: r["name"]):
        out.append("    {}: {},\n".format(
            json.dumps(repo["name"]), json.dumps(repo.get("base", ""))
        ))
    out.append("}\n\n")

    out.append("# The binary-seed closure: prebuilt Fedora rpms that cut the\n")
    out.append("# dependency graph.  This *is* the Fedora toolchain -- gcc,\n")
    out.append("# glibc, rpm macros and redhat-rpm-config all come from here,\n")
    out.append("# not from whatever the host happens to have installed.\n")
    out.append("SEED_RPMS = [\n")
    for entry in seed:
        out.append("    {},\n".format(_entry_literal(entry)))
    out.append("]\n\n")

    out.append("# Runtime closures, one per named image set.  A different\n")
    out.append("# question from SEED_RPMS over the same universe: what has to\n")
    out.append("# be installed for the machine to boot, rather than for the\n")
    out.append("# compiler to run.  These are installed by rpm with a real\n")
    out.append("# rpmdb and scriptlets, not unpacked.\n")
    out.append("IMAGE_SETS = {\n")
    for name in sorted(image_sets):
        out.append("    {}: [\n".format(json.dumps(name)))
        for entry in image_sets[name]:
            out.append("        {},\n".format(_entry_literal(entry)))
        out.append("    ],\n")
    out.append("}\n\n")

    out.append("# Source rpms replayed by rpmbuild -bb.\n")
    out.append("SOURCE_RPMS = [\n")
    for entry in sources:
        out.append("    {},\n".format(_source_literal(entry)))
    out.append("]\n\n")

    out.append("# One package() call per entry.\n")
    out.append("RECIPES = [\n")
    for entry in recipes:
        out.append("    {},\n".format(_recipe_literal(entry)))
    out.append("]\n\n")

    out.append("# Cycle staging.  A source package listed here is not built\n")
    out.append("# once but N times, each stage against the previous one's\n")
    out.append("# output, because it and its build dependencies form a cycle\n")
    out.append("# that buck2 would reject at parse time.  `cycle_deps_from`\n")
    out.append("# names the stage a cycle dependency is taken from -- \"seed\"\n")
    out.append("# meaning the pinned upstream binary.  Exactly one stage per\n")
    out.append("# source has ships=True; that is the one the plain target\n")
    out.append("# name aliases to.\n")
    out.append("STAGED = [\n")
    for entry in staged:
        out.append("    {},\n".format(_recipe_literal(entry)))
    out.append("]\n")
    return "".join(out)


def _entry_literal(entry):
    return json.dumps({
        "name": entry["name"],
        "evr": entry["evr"],
        "arch": entry["arch"],
        "location": entry["location"],
        "sha256": entry["sha256"],
        # Indexes REPO_BASE.  `location` alone is ambiguous: the same
        # package updated post-GA has the same repo-relative path under a
        # different tree, so without this an updated rpm would be fetched
        # from the GA base and 404.
        "repo": entry.get("repo") or "",
        "target": _target_name(entry),
    }, sort_keys=True)


def _source_literal(entry):
    return json.dumps({
        "name": entry["name"],
        "evr": entry["evr"],
        "location": entry["location"],
        "sha256": entry["sha256"],
        "repo": entry.get("repo") or "",
        "target": target_safe("srpm-{}".format(entry["name"])),
    }, sort_keys=True)


def _recipe_literal(entry):
    return _bzl_literal(entry)


def _bzl_literal(value):
    """Render a JSON-ish value as Starlark rather than as JSON.

    json.dumps is right for everything made of strings and is used above,
    but the two languages disagree about booleans -- JSON writes `false`,
    Starlark reads that as an undefined variable and the whole generated
    module fails to evaluate.  The staging entries carry a `ships` flag, so
    this is the first place the difference is reachable.
    """
    # Before the numeric check: in Python a bool *is* an int.
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, dict):
        return "{" + ", ".join(
            "{}: {}".format(_bzl_literal(k), _bzl_literal(v))
            for k, v in sorted(value.items())
        ) + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_bzl_literal(v) for v in value) + "]"
    return json.dumps(value)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lockfiles", nargs="+")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="where to write the .bzl (default: <flavor>/generated next to lock/)",
    )
    args = parser.parse_args(argv)

    for lockfile in args.lockfiles:
        with open(lockfile) as fh:
            lock = json.load(fh)

        if lock.get("schema") != LOCK_SCHEMA:
            sys.exit("{}: unsupported schema {} (this generator reads {}); "
                     "re-run tools/relock.py".format(
                         lockfile, lock.get("schema"), LOCK_SCHEMA))

        seed, image_sets, sources, recipes, staged = collect(lock)

        out_dir = args.out_dir
        if out_dir is None:
            # flavors/fedora/lock/x.lock.json -> flavors/fedora/generated/
            out_dir = os.path.join(
                os.path.dirname(os.path.dirname(os.path.abspath(lockfile))),
                "generated",
            )
        os.makedirs(out_dir, exist_ok=True)

        base = os.path.basename(lockfile).replace(".lock.json", "")
        out_path = os.path.join(out_dir, base + ".bzl")
        rel_lock = os.path.relpath(os.path.abspath(lockfile), os.getcwd())
        with open(out_path, "w") as fh:
            fh.write(render(
                lock, rel_lock, seed, image_sets, sources, recipes, staged,
            ))

        print(
            "{}: {} seed rpms, {} source rpms, {} recipes,"
            " {} staged, {} -> {}".format(
                lockfile, len(seed), len(sources), len(recipes), len(staged),
                ", ".join(
                    "{} in image {}".format(len(v), k)
                    for k, v in sorted(image_sets.items())
                ) or "no image sets",
                out_path,
            ),
            file=sys.stderr,
        )

        write_index(out_dir)


INDEX_HEADER = '''\
# @generated by tools/generate.py.  Do not edit.
#
# Starlark's load() is static -- it cannot be driven by a config value --
# but the set of releases to build is config-driven.  So every generated
# release is loaded here unconditionally and flavors/fedora/BUCK picks the
# ones `[buckos.fedora] releases` actually asks for out of this map.

'''


def write_index(out_dir):
    """Rewrite the index that maps a release onto its generated data."""
    releases = sorted(
        name[len("fedora-"):-len(".bzl")]
        for name in os.listdir(out_dir)
        if name.startswith("fedora-") and name.endswith(".bzl")
    )

    lines = [INDEX_HEADER]
    for release in releases:
        alias = "_r{}".format(release)
        lines.append(
            'load(\n'
            '    "//flavors/fedora/generated:fedora-{r}.bzl",\n'
            '    {a}_dist_tag = "DIST_TAG",\n'
            '    {a}_image_sets = "IMAGE_SETS",\n'
            '    {a}_recipes = "RECIPES",\n'
            '    {a}_release = "RELEASE",\n'
            '    {a}_repo_base = "REPO_BASE",\n'
            '    {a}_seed = "SEED_RPMS",\n'
            '    {a}_sources = "SOURCE_RPMS",\n'
            '    {a}_staged = "STAGED",\n'
            '    {a}_target_cpu = "TARGET_CPU",\n'
            ')\n'.format(r=release, a=alias)
        )

    lines.append("\nDATA_BY_RELEASE = {\n")
    for release in releases:
        alias = "_r{}".format(release)
        lines.append(
            '    "{r}": struct(\n'
            '        RELEASE = {a}_release,\n'
            '        DIST_TAG = {a}_dist_tag,\n'
            '        TARGET_CPU = {a}_target_cpu,\n'
            '        REPO_BASE = {a}_repo_base,\n'
            '        SEED_RPMS = {a}_seed,\n'
            '        IMAGE_SETS = {a}_image_sets,\n'
            '        SOURCE_RPMS = {a}_sources,\n'
            '        RECIPES = {a}_recipes,\n'
            '        STAGED = {a}_staged,\n'
            '    ),\n'.format(r=release, a=alias)
        )
    lines.append("}\n")

    index_path = os.path.join(out_dir, "index.bzl")
    with open(index_path, "w") as fh:
        fh.write("".join(lines))

    # A .bzl is only loadable if a package owns it.
    buck_path = os.path.join(out_dir, "BUCK")
    if not os.path.exists(buck_path):
        with open(buck_path, "w") as fh:
            fh.write(
                "# Package marker so the generated .bzl files here are "
                "loadable.\n# The data itself defines no targets; "
                "flavors/fedora/BUCK does that.\n"
            )


if __name__ == "__main__":
    main()
