#!/usr/bin/env python3
"""Generate pure Starlark data from a remote-upstream overlay lockfile."""

import argparse
import os
import re
import sys

from _lockfile import load_lockfile, strip_lockfile_suffix
from deb_generate import bzl_literal


SCHEMA = 1
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def validate_overlay(lock):
    if lock.get("schema") != SCHEMA:
        raise ValueError("unsupported upstream overlay schema: {}".format(lock.get("schema")))
    if lock.get("family") not in ("deb", "rpm"):
        raise ValueError("unsupported overlay package family: {!r}".format(lock.get("family")))
    if not NAME_RE.fullmatch(lock.get("name", "")):
        raise ValueError("invalid overlay name: {!r}".format(lock.get("name")))
    base = lock.get("base", {})
    for field in ("architecture", "flavor", "image_set", "release", "sha256"):
        if not base.get(field):
            raise ValueError("overlay base is missing {}".format(field))
    if len(base["sha256"]) != 64:
        raise ValueError("overlay base sha256 is malformed")
    if not lock.get("packages"):
        raise ValueError("overlay contains no resolved packages")


def render(lock, source):
    return "\n".join([
        "# @generated by tools/upstream_generate.py from {}".format(source),
        "# Do not edit by hand.",
        "",
        "OVERLAY = struct(",
        "    BASE = {},".format(bzl_literal(lock["base"], 4)),
        "    CHANGES = {},".format(bzl_literal(lock.get("changes", {}), 4)),
        "    FAMILY = {},".format(bzl_literal(lock["family"])),
        "    NAME = {},".format(bzl_literal(lock["name"])),
        "    PACKAGES = {},".format(bzl_literal(lock["packages"], 4)),
        "    REPOSITORIES = {},".format(bzl_literal(lock.get("repositories", []), 4)),
        "    REQUESTED_PACKAGES = {},".format(bzl_literal(lock.get("requested_packages", []), 4)),
        ")",
        "",
    ])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lockfile")
    parser.add_argument("--output", default=None)
    args = parser.parse_args(argv)
    lock = load_lockfile(args.lockfile)
    try:
        validate_overlay(lock)
    except ValueError as error:
        parser.error(str(error))
    output = args.output or strip_lockfile_suffix(args.lockfile) + ".bzl"
    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as stream:
        stream.write(render(lock, args.lockfile))
    print("{} -> {}".format(args.lockfile, output), file=sys.stderr)


if __name__ == "__main__":
    main()
