load("//defs:flavor.bzl", "package")
load("//defs:releases.bzl", "default_release", "flavor_releases")
load(
    "//defs:rpm_family.bzl",
    "rpm_buildroot_target",
    "rpm_buildroots_for",
    "rpm_downloads_for",
    "rpm_packages_for",
    "rpm_rootfs_for",
)
load("//flavors/centos-hyperscale/generated:index.bzl", "DATA_BY_RELEASE")

RELEASES = flavor_releases("centos-hyperscale", default = "9,10")
DEFAULT_RELEASE = default_release("centos-hyperscale", RELEASES)

rpm_downloads_for("centos-hyperscale", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
rpm_buildroots_for("centos-hyperscale", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
rpm_packages_for("centos-hyperscale", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)
rpm_rootfs_for("centos-hyperscale", RELEASES, DEFAULT_RELEASE, DATA_BY_RELEASE)

package(
    name = "hello-9",
    flavor = "centos-hyperscale",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos-hyperscale", "-9"),
    supplier = "Organization: CentOS",
    visibility = ["PUBLIC"],
)

package(
    name = "hello-10",
    flavor = "centos-hyperscale",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos-hyperscale", "-10"),
    supplier = "Organization: CentOS",
    visibility = ["PUBLIC"],
)

package(
    name = "hello",
    flavor = "centos-hyperscale",
    srpm = "//tests:hello-srpm",
    source_name = "hello",
    version = "1.0",
    release = "1",
    subpackages = ["hello"],
    defines = ["debug_package %{nil}"],
    buildroot = rpm_buildroot_target("centos-hyperscale", ""),
    supplier = "Organization: CentOS",
    visibility = ["PUBLIC"],
)
